### PR TITLE
ISC: wrap text

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by paultag** [comment]
@waldyrious mind updating this? I merged another PR, but this one was looking good to me :)

**Comment by waldyrious** [comment]
Sure, I'll do it in a minute.

**Comment by paultag** [comment]
Thanks!!

**Comment by waldyrious** [comment]
@paultag done, but you might want to uncheck the option "Require branches to be up to date before merging" in https://github.com/OpenSourceOrg/licenses/settings/branches/master, because that setting prevents concurrent PRs (i.e. based on the same commit from master) to exist without the whole rebase / push --force dance for all but the first one merged, and this IMHO detracts from the contribution experience needlessly. To clarify what I mean by "needlessly": there were no conflicts between this commit and the changes made in master since it was created (in fact the other PR didn't even touch on the same files as this one), but that setting tells github to treat the outdatedness as if it were an error.

Note that turning that off still keeps the error when there are actually conflicts that prevent a merge, so that case would still be properly handled.

**Comment by paultag** [comment]
@waldyrious so, I 100% agree in theory - but the nice thing about this is it means that all branches have to be passing master before merge -- it could be the case where each PR is passing in isolation, but when one is landed, the other breaks (e.g. missing a vital bit of dataset that was added in one PR)

If this keeps happening I might do that, but for now, I'm tempted to leave it as-is, just to be sure CI passes :) :+1: 

Thanks for the suggestion, though! Great idea. I'll keep it in mind.

**Comment by waldyrious** [comment]
> If this keeps happening I might do that

That's the problem, this will *by definition* happen every time, if that setting remains activated -- that's exactly what it does. For instance, if you have N PRs open, you can only merge 1 and then ask (and wait) for the remaining N-1 PRs to be rebased & force-pushed; then the same thing for the N-2 remaining ones after you merge the second one, and so on. Sure, you could only ask for that in the order you plan to merge the PRs, but there's no guarantee that the author will comply quickly (or at all), and it's simply too cumbersome for both the contributors and the maintainers, for little benefit IMO. We had this problem in a popular repo I help maintain ([tldr-pages/tldr](https://github.com/tldr-pages/tldr)), and we quickly realized that managing PRs that way was unsustainable.

Note that if CI passes when a PR is first created, it's not very likely that another PR that got merged meanwhile would interfere with the results of the CI tests for the first PR. Of course, there are cases where this could happen, but making the default flow harder for the sake of the exceptional circumstances is not worth the costs. I offer that it should be a maintainer's task to recognize cases where this could actually happen, and ask the authors of the affected PRs to rebase.

Given the above, I'd ask you to reconsider :)

**Comment by waldyrious** [comment]
Hey @paultag, I'd love to hear your thoughts regarding my previous comment, once you get the chance to respond :)

**Pull request merged**
