### PR TITLE
Add license PHP-3.01

### PR DESCRIPTION
**Pull request by goneall**
License text and name copied from OSI web page.

This license is listed in issue #62

Signed-off-by: Gary O'Neall <gary@sourceauditor.com>

### CODE REVIEW

**Comment by webmink** [comment]
@goneall I think licenses/spdx/importedSpdxFiles.json has updated - can you check the unresolved conflict? It appears to be blocking all your commits.

**Comment by goneall** [comment]
@webmink It looks like I'll get a merge conflicts every time one of these gets merged.  I'll go through and resolve all the current conflicts, but I'll probably need to do this for every merge.  Just ping me once they get merged and I'll resolve.

In the future, I can either batch several of the changes together or just do one at a time.  Let me know if you have a preference on the approach.

**Comment by webmink** [comment]
@goneall This one still has a conflict even after the fix...

**Comment by goneall** [comment]
@webmink - This is going to happen after every merge.  Every time we merge one of the new PR's, it's going to cause a new merge conflict for all the others.

Just ping me after every merge and I'll resolve a merge conflict for the next one.

In the future, I'll batch multiple updates in a single PR to avoid this rather painful process.

**Pull request merged**
