### PR TITLE
add wikipedia page for the ISC license

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by paultag** [comment]
Awesome, thank you!

**Comment by paultag** [comment]
I'll deploy this to the API when I can get back on personal hardware :)

**Comment by waldyrious** [comment]
That was quick, thanks @paultag :)

One question, by the way: is there a particular reason the actual text of the licenses isn't kept in this repo?

**Comment by paultag** [comment]
@waldyrious They are, but I had to scrape it, https://github.com/OpenSourceOrg/licenses/blob/master/texts/plain/ISC - want to clean it up to make it nice? :D

**Comment by waldyrious** [comment]
Sure :) but that isn't really the source used in the website, is it? Do the texts need to be synchronized manually? :/

As for cleaning it up, is it OK if I change the placeholders to use the same style used in the [MIT license](https://github.com/OpenSourceOrg/licenses/blob/master/texts/plain/MIT) -- i.e. `<YEAR>, <OWNER>`?

Also, can I add the title of the licence, e.g. like in http://choosealicense.com/licenses/isc/? That would make locating the file easier (both in this repo and in others that use the license).

**Comment by paultag** [comment]
@waldyrious It will be, but isn't currently - I'm still hacking out the data quality issues, then I'll be hacking a plugin to pull that into the OSI site. It'll be canonical soon!

Yeah, let's do that, but lets stay consistent - as for the title, I'm a bit undecided, but I don't see the harm in it (and easy to change later), so I'd say, sure!

**Comment by waldyrious** [comment]
> I'm still hacking out the data quality issues, then I'll be hacking a plugin to pull that into the OSI site.

Awesome news! Let me know if there are small tasks I (or others) can help with :)

**Comment by paultag** [comment]
@waldyrious deployed! Will do!

**Pull request merged**
