### PR TITLE
Update MirOS licence body from MirBSD CVS

### PR DESCRIPTION
**Pull request by mirabilos**
From latest MirBSD CVS: update external links and surrounding text
(no changes to the licence itself)

This is also in preparation of extending the HTML page with more resources related to the licence.

Furthermore, add tl;dr-legal link, while here anyway

### CODE REVIEW

**Comment by paultag** [comment]
It seems like this license has changed a bit.

Is there a versioning scheme? @richardfontana - we should talk about this during the BoD meeting

**Comment by mirabilos** [comment]
Paul Tagliamonte dixit:

>It seems like this license has changed a bit.

It doesn’t, and it shouldn’t.
Where do you see a change in the actual licence?
(As opposed to the accompanying documentation.)

**Comment by webmink** [comment]
We're returning to this project now OSI is getting staffed. @mirabilos would you like to resubmit?

**Comment by mirabilos** [comment]
Simon Phipps dixit:

>We're returning to this project now OSI is getting staffed. @mirabilos
>would you like to resubmit?

I guess, but only in a week or so, I’m otherwise occupied the next
few days.

**Comment by mirabilos** [comment]
@webmink done

**Pull request merged**
