### PR TITLE
Replace "texts/plain/OFL-1.1" with the canonical plain-text version from http://scripts.sil.org/cms/scripts/render_download.php?format=file&media_id=OFL_plaintext&filename=OFL.txt

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by tianon** [comment]
This will be much easier to review in no-whitespace form: https://github.com/OpenSourceOrg/licenses/pull/20/files?w=1 :smile:

**Comment by tianon** [comment]
Happy to amend to include 1.0 too, but wanted to make sure this was going to be the right direction before I did too much work on it. :innocent:

**Comment by tianon** [comment]
```console
$ diff -u \
    <(curl -s 'http://scripts.sil.org/cms/scripts/render_download.php?format=file&media_id=OFL_plaintext&filename=OFL.txt') \
    <(curl -s 'https://raw.githubusercontent.com/tianon/licenses/ofl-plain/texts/plain/OFL-1.1')
$ echo $?
0
```

**Comment by tianon** [comment]
Oh, 1.0 doesn't exist in the repo yet, and is 404 on http://opensource.org/licenses/OFL-1.0. :+1:

**Comment by tianon** [comment]
(still happy to rebase/amend/whatever and to work on 1.0, but since it's not listed on the site, I'm guessing that means it's not verified as "open source")

**Comment by paultag** [comment]
Thanks, @tianon! This is awesome. Thanks a ton!

**Comment by tianon** [comment]
My pleasure! :+1:

**Pull request merged**
